__author__ = 'CSI-USER'

SPINNER_SLEEP = 0.1
SESSION_KEEPER_TIMEOUT = 30
SUCCESS_RESPONSE_CODE = 200
SUCCESS_STATE = 'success'
DEFAULT_GUEST_USERNAME = 'CSI-USER'
DEFAULT_GUEST_PASSWORD = 'Password1!'
